### ISSUE TITLE
Network change defect

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd-android#13]
```
<Дремучий_Шаман> i2pd говорят хуёво смену сети отрабатывает
<Дремучий_Шаман> приходится рестарт и2пд делать
```

**Comment by wipedlifepotato** [comment]
Отлавливать состояние в андроиде, если что-то сменилось, то пробовать, через некоторое время: "stopDaemon, startDaemon"?

**Comment by wipedlifepotato** [comment]
Либо научить сам i2pd замечать такие вещи, например смену локального/внешнего IP? Если он ещё не умеет, конечно.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@r4sas короче я думаю с нестандартными Андройдами не стоковыми отдельная песня, пускай их поддерживают те кто желает, в своём софте.
