### ISSUE TITLE
android - checkbox "start on operating system boot"

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd-android#14]

**Comment by wipedlifepotato** [comment]
https://github.com/PurpleI2P/i2pd-android/pull/19 need to be checked
проверить надо.

**Comment by wipedlifepotato** [comment]
@nonlinear-chaos-order-etc-etal https://github.com/wipedlifepotato/i2pd-android/releases/tag/0.0 test it please

**Comment by asmexcaliburwoods** [comment]
@wipedlifepotato a bit later, currently very busy

**Comment by wipedlifepotato** [comment]
@asmexcaliburwoods @nonlin-lin-chaos-order-etc-etal

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
SUPERSEDED BY https://github.com/PurpleI2P/i2pd-android/pull/19
