### ISSUE TITLE
2.38.0: теперь часто "приложение не отвечает - закрыть - подождать"

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd-android#25]
<ИНЕИСТЫЙЪЬ_ВЕЛИКАНЪЬ_ХРАНИМИРЪЬ> вы чот нахимичили с и2пд под андройд. теперь часто "приложение не отвечает - закрыть - подождать"

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
неплазег пусть чинит

**Comment by wipedlifepotato** [comment]
Что за телефон?

**Comment by wipedlifepotato** [comment]
Что ты делаешь что он "не отвечает"?
Я сейчас тыкаю, нету такого

**Comment by wipedlifepotato** [comment]
adb logcat?

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@wipedlifepotato 

> Что за телефон?
Brand: Sony XPERIA XA2 Ultra
Model name: H4213

Версию андройда скрин ща скину

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
Android 9

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@wipedlifepotato 

> Что ты делаешь что он "не отвечает"?
> Я сейчас тыкаю, нету такого

У меня соседские дети брали погонять и вернули что и2пд не отвечал.. т.е. ответ: хз

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@wipedlifepotato 

создан каталог '/home/user/tmp/i2pdandroidissue25/logs'
`./adb -d logcat -d > /home/user/tmp/i2pdandroidissue25/logs/logcat.stdout.txt 2> /home/user/tmp/i2pdandroidissue25/logs/logcat.stderr.txt`

в телеграме сброшу

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@wipedlifepotato 

а вот хрен, пусто:

```
cat logcat.std* | grep -i i2p | wc -c 
0
```

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
крч ставьте needinfo и можете закрыть. появится инфа - переоткроем тикет

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
удалён 'i2pdandroidissue25/logs/logcat.stdout.txt.gz'

удалён 'i2pdandroidissue25/logs/logcat.stderr.txt'

в телеграме у плаза копия stdout осталась
