### ISSUE TITLE
App not opening.

### ISSUE THREAD

**Issue by vartiovaara** [PurpleI2P/i2pd-android#34]
Installed 2.40.0 from F-Droid. When opening, the app closes almost immediately.

**Comment by r4sas** [comment]
What Android version are you using?
Can you fetch logcat output from device?

**Comment by vartiovaara** [comment]
I am using Android 11 with "5 December 2021" security updates on an Oneplus Nord 2 5G.
Output from command "adb logcat | grep i2pd": https://pastebin.com/5csTWunC

**Comment by r4sas** [comment]
Have you enabled `[meshnets] yggdrasil` option?

**Comment by r4sas** [comment]
ref: https://github.com/PurpleI2P/i2pd/commit/0062f7d76492bce70d76ca1f22c67cc18ff5b8f8

But full stack is still needed, maybe here's problem with android-ifaddrs.

**Comment by vartiovaara** [comment]
> Have you enabled [meshnets] yggdrasil option?
I honestly don't know whether it is enabled. I just installed it an am unable to run it. Never changed any settings or parameters.

**Comment by r4sas** [comment]
> I honestly don't know whether it is enabled. I just installed it an am unable to run it. Never changed any settings or parameters.

Okay. I see that code used for reseeding tried to detect if yggdrasil present even if it is disabled (fixed in code below).
Cay you try start app again and get full crash dump from adb?
Just start `adb logcat`, start app and get full log of crash.

**Comment by r4sas** [comment]
Issue found, update will be pushed on next week with new release.

**Comment by r4sas** [comment]
2.41.0 released. F-droid must detect release and update package, that can take 1-2 days.
