### ISSUE TITLE
use the non-gui daemon as an external OS process

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd-android#40]
андроед достал убивать и2пд. надо безгуевого линукс демона в гуевую прогу внедрить чтоб гуи рожал вечноживой процесс и цеплялся потом к нему

почитать про интерпроцессную коммуникацию для андроид

**Comment by r4sas** [comment]
Выруби DuraSpeed и всё встанет на свои места.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
маленький букмарклет

комментарии unknown'a (README): https://github.com/PurpleI2P/i2pd/commit/d5214099c5f3c43b2282ca4c0d1cf33b67a98660

gha https://github.com/PurpleI2P/i2pd-android/blob/master/.github/workflows/android.yml

папка сборки https://github.com/PurpleI2P/i2pd-android/tree/master/binary/jni

вспомогательные скриптики https://github.com/PurpleI2P/i2pd-android/tree/master/contrib/binary_pack

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
DuraSpeed et al (app killing stuffs): https://github.com/urbandroid-team/dont-kill-my-app/issues/57

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
see also https://github.com/Gedsh/InviZible/wiki#prevent-invizible-from-being-killed-by-android

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
see also for XIAOMI https://github.com/Gedsh/InviZible/issues/144#issue-1289533367

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
https://stackoverflow.com/questions/70788254/child-process-should-not-die-with-parent-process

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
experimenr 2

"So, the system may kill the process at any time to reclaim memory, and in doing so, it terminates the spawned thread running in the process. The solution to this problem is typically to schedule a [JobService](https://developer.android.com/reference/android/app/job/JobService) from the BroadcastReceiver, so the system knows that there is still active work being done in the process."

Source for the quote: https://developer.android.com/guide/components/activities/process-lifecycle

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
https://www.woolha.com/tutorials/android-using-jobservice-jobscheduler-for-running-repeated-background-jobs

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
https://developer.android.com/reference/android/app/job/JobService Added in [API level 21](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
Related and superseded by #50.
