### ISSUE TITLE
subscriptions.txt

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd-android#74]
@r4sas, в ассетах нет subscriptions.txt

https://github.com/PurpleI2P/i2pd-android/tree/master/app/src/main/assets

но он пытается его копировать

https://github.com/PurpleI2P/i2pd-android/blob/ca3ef80981ccdca19d84c94783e92784135fac29/app/src/main/java/org/purplei2p/i2pd/DaemonWrapper.java#L257

**Comment by r4sas** [comment]
> subscriptions.txt уже 100 лет как легаси
> просто выпилить
